use common::models::Alert;
use leptos::prelude::*;

use crate::api::client::ApiClient;
use crate::components::icons::IconDownload;
use crate::components::AlertsTable;

#[component]
pub fn AlertsPage(
    alerts: ReadSignal<Vec<Alert>>,
    set_alerts: WriteSignal<Vec<Alert>>,
) -> impl IntoView {
    let on_export_csv = move |_| {
        leptos::task::spawn_local(async move {
            let _ = ApiClient::export_csv_file().await;
        });
    };

    view! {
        <div class="space-y-6">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-ink-700">
                <div>
                    <h1 class="text-2xl font-bold text-white tracking-tight">
                        "Threat incidents"
                    </h1>
                    <p class="text-xs text-ink-500 mt-1">
                        "Inspect alerts generated by detection rules, acknowledge findings, and mark resolved."
                    </p>
                </div>
                <div class="flex items-center gap-2.5">
                    <button
                        on:click=on_export_csv
                        class="px-3.5 py-2 rounded-md bg-ink-900 hover:bg-ink-800 text-slate-200 text-xs font-semibold border border-ink-600 transition-colors flex items-center gap-2"
                    >
                        <IconDownload class="w-3.5 h-3.5".to_string() />
                        <span>"Export CSV"</span>
                    </button>
                </div>
            </div>

            <AlertsTable alerts=alerts set_alerts=set_alerts />
        </div>
    }
}
