use common::models::Alert;
use leptos::prelude::*;

use crate::api::client::ApiClient;
use crate::components::AlertsTable;

#[component]
pub fn AlertsPage(
    alerts: ReadSignal<Vec<Alert>>,
    set_alerts: WriteSignal<Vec<Alert>>,
) -> impl IntoView {
    let on_export_csv = move |_| {
        leptos::task::spawn_local(async move {
            let _ = ApiClient::export_csv_file().await;
        });
    };

    view! {
        <div class="space-y-6">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 class="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2.5">
                        <span>"🚨"</span>
                        "Threat Incidents & SOC Triage"
                    </h1>
                    <p class="text-xs text-slate-400 mt-1">
                        "Inspect alerts generated by detection rules, acknowledge findings, and mark resolved."
                    </p>
                </div>
                <div class="flex items-center gap-2.5">
                    <button
                        on:click=on_export_csv
                        class="px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 text-xs font-semibold border border-slate-700/80 shadow-sm transition flex items-center gap-2"
                    >
                        <span>"📥"</span>
                        <span>"Export CSV"</span>
                    </button>
                </div>
            </div>

            <AlertsTable alerts=alerts set_alerts=set_alerts />
        </div>
    }
}
